[project]
name = "dapr-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dapr==1.15.0",
    "dapr-ext-fastapi>=1.15.0",
    "fastapi[standard]>=0.115.12",
    "uv>=0.6.14",
]
